name: dokcer pipeline

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
      CONTAINER_NAME: test-app
      PORT: 4000

    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build image
        run: |
          docker build -t $IMAGE_NAME .

      - name: image tag
        run: |
          docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.sha }}
     
      - name: push image
        run: |
          docker push $IMAGE_NAME

      - name: deploy to gcp
        uses: google-github-actions/auth@v2 
        with:
          workload_identity_provider: "projects/302992184606/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-deployer@project-4fb5f513-2a02-47c0-af8.iam.gserviceaccount.com"

      - name: setup gcp sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: deploy to gcp vm
        run: |
         gcloud compute ssh docker-vm \
           --zone us-central1-f \
           --command " 
             sudo docker pull $IMAGE_NAME
             sudo docker stop $CONTAINER_NAME || true
             sudo docker rm $CONTAINER_NAME || true

             sudo docker run -d \
                    --restart always \
                    --name "$CONTAINER_NAME" \
                    -p "$PORT:4000" \
                    "$IMAGE_NAME"
             
             sudo docker ps
           " 
