name: dokcer pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
      CONTAINER_NAME: test-app
      PORT: 4000

    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build image
        run: |
          docker build -t $IMAGE_NAME .

      - name: image tag
        run: |
          docker tag $IMAGE_NAME ${{ secrets.DOKCERHUB_USERNAME }}/anotherwhisk:${{ github_sha }}
     
      - name: push image
        run: |
          docker push $IMAGE_NAME

      - name: deploy to gcp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
             docker pull $IMAGE_NAME
             docker stop $CONTAINER_NAME || true
             docker rm $CONTAINER_NAME || true

             dokcer run -d \
                    --restart-always \
                    --name $CONTAINR_NAME \
                    -p $PORT:4000 \
                    $IMAGE_NAME
            docker ps 
